- examples/autobahn-server.rs
- examples/client.rs
- examples/server.rs
- src/client/mod.rs
- src/message.rs
- src/result.rs
- src/server/mod.rs
- src/stream.rs
- src/ws/util/dataframe.rs
- src/ws/util/header.rs
This gets the library up to date with the latest rustc.
> io -> old_io, write -> write_all

- Cargo.toml
- README.md
- src/ws/util/dataframe.rs
Missed this last night when moving to the new std::io module.
> Close #18: Fix dataframe implementation

- src/client/mod.rs
- src/lib.rs
- src/server/mod.rs
No more of that ugly red ribbon :)
> Fix the build

- src/ws/util/url.rs
This just make some lines smaller, and hopefully more maintainable.
> Small cleanup of url.rs to take advantage from From trait defitions

- src/ws/util/header.rs
https://github.com/rust-lang/bitflags/commit/133a3a4b2f0ff383fab3042d39b9d94a15024a52
> Bitflags has its own debug impl now

- Cargo.toml
This is the band-aid fix for #44.
> pin hyper to fix compile error

- src/server/request.rs
This means we also include a `method` field on the `Request` structure. For all valid websocket upgrade requests, this will be equal to `Method::Get`.
I made this change because I wanted to be able to do custom handling of non-websocket Requests.
```rust
let request = connection.read_request().unwrap();
if request.validate().is_ok() {
// handle as a websocket upgrade request
// ...
} else {
// handle like a REST request, for instance
// ...
}
```
Summary:
* Previous behavior: reject all non-GET requests during `read_request()`.
* New behavior: wait to check HTTP method until `Request.validate()`.
> Move HTTP method validation to Request.validate()

- Cargo.toml
> Require explicit versions for all dependencies

- Cargo.toml
- src/client/mod.rs
- src/server/mod.rs
Please also publish on crates.io
CC https://github.com/servo/servo/pull/8446
> Update dependencies with breaking changes

- src/client/response.rs
- src/receiver.rs
- src/sender.rs
- src/server/response.rs
This PR fixes #61, but I think it can break clients.
> Server masking rules fixed

- Cargo.toml
> Update openssl dependency

- Cargo.toml
- src/result.rs
If it is ok, would you please release a new version?
> Upgrade byteorder to 0.5.1

- Cargo.toml
No code changes were required.
> Update to byteorder 1.0

- Cargo.toml
> Bump to 0.17.2 (nonblock)

- .travis.yml
> Update travis to run autobahn tests.

- examples/autobahn-server.rs
- examples/hyper.rs
- examples/server.rs
- src/server/mod.rs
- src/server/upgrade/mod.rs
This should also fix the autobahn tests for the server
Fixes #104
> Fix server incoming client iterator.

- src/client/mod.rs
- src/receiver.rs
> Return any impl of Message in recv_message

- examples/client.rs
- src/client/mod.rs
- src/dataframe.rs
- src/header/accept.rs
- src/header/extensions.rs
- src/header/key.rs
- src/header/origin.rs
- src/header/protocol.rs
- src/lib.rs
- src/message.rs
- src/receiver.rs
- src/server/upgrade/mod.rs
- src/stream.rs
- src/ws/dataframe.rs
- src/ws/util/header.rs
Let me know if anything should be reverted to match personal preference.
> Fix up some issues indicated by clippy

- src/client/builder.rs
Make it actually useful in multi-threaded environment.
> Return Box<... + Send> from ClientBuilder::connect

- .travis.yml
- README.md
- src/client/builder.rs
- src/client/sync.rs
- src/codec/ws.rs
- src/dataframe.rs
- src/header/extensions.rs
- src/lib.rs
- src/message.rs
- src/receiver.rs
- src/sender.rs
- src/server/sync.rs
- src/server/upgrade/async.rs
- src/server/upgrade/mod.rs
- src/server/upgrade/sync.rs
- src/ws/dataframe.rs
- src/ws/receiver.rs
- src/ws/util/header.rs
- src/ws/util/mask.rs
> Use clippy for the CI

- src/server/upgrade/mod.rs
moved to this PR so it can be rebased, original is #161
> Expose the original request URI prior to UPGRADE

- Cargo.toml
- examples/async-autobahn-client.rs
- src/client/builder.rs
PR #143 had styling errors, quick fix PR.
> Fix styling errors in previous PR.

- src/client/builder.rs
- src/server/upgrade/mod.rs
- src/ws/dataframe.rs
write_fmt will repeatedly call write_str and send mutli tcp package
> fix send extra tcp package

- README.md
> Update Version Number

- examples/async-autobahn-client.rs
- examples/async-client.rs
- examples/autobahn-server.rs
- examples/hyper.rs
- examples/parallel-server.rs
- examples/server.rs
- examples/ssl-client.rs
> Remove useess move closures in examples

- examples/async-server.rs
> Add handling of incomplete handshakes into examples/async-server

- src/server/async.rs
Closes: https://github.com/websockets-rs/rust-websocket/issues/206
Now `async::Server::incoming(self) -> Incoming<TlsStream<TcpStream>>` will return a concurrent Stream of incoming clients.
Assume there are clients A and B. Client A connects first with `telnet` and maliciously does not send any data, client B connects to server and tries to perform WebSocket handshake as a good guy.
An example server:
```
server
.incoming() // 1
.for_each(move |(upgrade, addr)| {
// 2
}
```
Before PR: the server stuck on client A in `// 1`, client B hung, waiting his queue to perform a handshake forever.
After PR: client B performs handshake first and passes into `// 2`, whereas client A may maliciously sleep in `// 1` as long as he wants.
This fix implemented using …
> Make async::Server::incoming concurrent

- src/server/async.rs
rustfmt changed and the current code does not match its rules
> Fix server::async fmt by rustfmt

- examples/async-autobahn-server.rs
- examples/async-server.rs
- examples/parallel-server.rs
https://github.com/websockets-rs/rust-websocket/issues/207
update the examples
> update examples async->r#async

- .travis.yml
- README.md
- src/client/builder.rs
- src/dataframe.rs
- src/lib.rs
- src/message.rs
- src/server/upgrade/mod.rs
Update deprecated lint names and remove unnecessary cfg_attr(cargo-clippy)
> Fix clippy attributes

- websocket-base/LICENSE
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> Add LICENSE into a websocket-base sub-crate
