- src/result.rs
There was a trivial cast warning that should now be fixed. Also, all indentation in src/result.rs has been converted to tabs.
> Remove cast warning and fix indentation in src/result.rs

- examples/autobahn-client.rs
- src/lib.rs
The build fails due to the changes introduced by RFC 940.
> Strip hyphens from `extern crate`

- src/client/receiver.rs
- src/client/request.rs
- src/client/response.rs
This should fix the failing autobahn tests for the client. There might be a better way of doing this?
> Use BufReader in client::Request

- src/ws/util/dataframe.rs
this fixes a bug I was having where some datagrams where not delivered until some other event happens to fill the buffer or flush the stream.
> Fix dataframes not being sent

- src/client/request.rs
- src/client/response.rs
- src/result.rs
rust-websocket is currently broken since hyper upgraded to 0.4.0.
I attempted to fix the issues, but now I am getting an ICE on the latest rust nightly build.
```
rustc --version
rustc 1.1.0-nightly (7bd71637c 2015-05-06) (built 2015-05-06)
```
> update to Hyper 0.4.0

- src/client/response.rs
- src/message.rs
Hey again! Just wanted to add a small tweak, I noticed sometimes a string gets made describing an error even when there is no error! This is expensive and should be stopped!
I haven't noticed any error description that isn't a `&'static str`, maybe all the errors should just  use that instead of `String`.
> Postpone some to_string calls to happen only during an error

- src/client/mod.rs
- src/client/receiver.rs
- src/client/sender.rs
- src/server/mod.rs
- src/server/receiver.rs
- src/server/sender.rs
- src/stream.rs
While fixing #28, I though of a few questions:
1. What is the point of having different client & server implementations of receiver & sender?
2. Would it make more sense if the server gave out a `Client` on a new connection?
3. I would like to use this library with mio, I'm working on putting this under a feature [here](https://github.com/illegalprime/rust-websocket/tree/mio). Do you think this is a good idea?
4. Maybe this library is better off parting with `hyper` since its such a giant library? I think I see it used for only headers.
5. What is the point of having different client & server implementations of request & response?
I ask because there is a rust websocket library claiming to be lightweight, and I want this one to be the main library. There is also one that boasts to support …
> this PR comes with questions

- src/client/mod.rs
This is a breaking change for people who rely on the current name.
> Fix spelling in get_{mut_,}reciever

- src/client/response.rs
- src/receiver.rs
- src/server/response.rs
Fix issue where first websocket messages can be consumed during
handshake and never sent to server.
Fix for #72
> send BufReader instead of stream to reciever

- Cargo.toml
- src/ws/util/url.rs
<s>**Do not merge yet:** rust-url 1.0 is not published yet and may still get breaking changes. The goal of this PR for now is to demonstrate API usage.</s>
Depends on:
* https://github.com/servo/rust-url/pull/176
* https://github.com/alexcrichton/cookie-rs/pull/42
* https://github.com/hyperium/hyper/pull/740
> Update to rust-url 1.0

- src/receiver.rs
- src/sender.rs
- src/server/mod.rs
- src/stream.rs
This has to do with: https://github.com/cyderize/rust-websocket/issues/81
I added a `set_nonblocking` method to the `Server` so it is possible to make accepting connections not block, and added a `set_nonblocking` method to `Receiver<WebSocketStream>` so it is possible to make receiving messages not block.
Documentation, examples and tests still need to be written.
> Adding ability to accept connections and receive messages without blocking.

- src/dataframe.rs
Avoid calling `std::io::read_one_byte` for each byte, go from 30 MiB/s to 200 MiB/s.
> Optimize reading bytes in DataFrame

- Cargo.toml
This is a temporary strengthening of the hyper version because of a
needed upstream change. It will be removed when it becomes a part of an
official version.
> Only use specific git rev for hyper

- Cargo.toml
- examples/autobahn-client.rs
- src/header/accept.rs
- src/header/key.rs
- src/lib.rs
See #118, rustc-serialize is gone.
I didn't need serde for any of the stuff within the main library, because the only thing rustc-serialize was being used for was base64 encoding and decoding - the base64 crate was used instead.
I have added serde_json as a dev dependency, because there was some json decoding in the autobahn client.
Let me know what you think?
> removed rust serialize

- src/client/builder.rs
- src/codec/ws.rs
- src/dataframe.rs
- src/receiver.rs
Fixes #119 , also fixes a small inefficiency, adds tests, removes unneeded TODOs
> Dataframe reads all of payload.

- .travis.yml
- examples/autobahn-client.rs
- src/client/builder.rs
- src/client/sync.rs
- src/codec/ws.rs
- src/dataframe.rs
- src/header/accept.rs
- src/header/extensions.rs
- src/message.rs
- src/receiver.rs
- src/result.rs
- src/server/sync.rs
- src/server/upgrade/mod.rs
- src/ws/dataframe.rs
- src/ws/util/header.rs
- src/ws/util/mod.rs
See #110 - replaced `try!` with `?`
Thoughts?
> Use the ? operator

- src/server/upgrade/mod.rs
I need to access this primitive. The API seems reasonable for public consumption and exposing it doesn't uncover any internal types.
> Expose websocket::server::upgrade::validate

- Cargo.toml
- examples/async-autobahn-client.rs
- src/client/builder.rs
`base64`: previously websocket had to be built with two versions of base64 (0.5 and 0.6) to support both its own use and hyper's.
`Future::boxed`: see https://github.com/alexcrichton/futures-rs/issues/556.
> Update base64 and replace use of deprecated Future::boxed

- src/client/async.rs
- src/result.rs
- src/server/async.rs
- src/server/upgrade/async.rs
Tokio's executor trait requires `Send` to be implemented on the future to be spawned.
> Add Send trait bounds to the Futures

- src/client/builder.rs
`url.host_str()` returns IPv6 adresses surrounded with square brackets, which does not work with ToSocketAddrs.
> Rewrite extract_host_port to work with IPv6 addresses

- Cargo.toml
- src/client/builder.rs
- src/result.rs
- src/server/async.rs
- src/server/sync.rs
Native-tls 0.1 uses outdated `openssl` crate that doesn't build with OpenSSL 1.1.1 (Arch Linux is already using it and openSUSE Tumbleweed will update in a few days).
Updating native-tls also fixes few issues with static OpenSSL builds.
It throws warnings like:
```
warning: use of deprecated item 'tokio_io::AsyncRead::framed': Use tokio_codec::Decoder::framed instead
--> src/server/upgrade/async.rs:221:5
|
221 |             .framed(HttpServerCodec)
|  
```
But I couldn't manage to fix them.
> Update native-tls and tokio-tls

- Cargo.toml
- examples/async-autobahn-client.rs
- examples/async-autobahn-server.rs
- examples/async-client.rs
- examples/async-server.rs
- examples/client.rs
- examples/parallel-server.rs
- examples/ssl-client.rs
- src/client/async.rs
- src/client/builder.rs
- src/codec/http.rs
- src/codec/ws.rs
- src/lib.rs
- src/receiver.rs
- src/server/async.rs
- src/server/sync.rs
- src/server/upgrade/async.rs
- src/server/upgrade/mod.rs
- src/stream.rs
- src/ws/util/mod.rs
> Use tokio 0.1 (tokio reform updates)

- .travis.yml
- src/message.rs
This adds `From<String>` & `From<Vec<u8>>` for OwnedMessage. Note that this means that it is impossible for a `Vec<u8>` message to be implicitly converted into a `OwnedMessage::Ping` or a `OwnedMessage::Pong`. This would fix #203.
> Added From<String> & From<Vec<u8>> for OwnedMessage

- src/stream.rs
The current `impl<T: AsTcpStream> AsTcpStream for Box<T>` requires `T: Sized`. This means that anyone using `ClientBuilder::connect` will not be able to call the various `shutdown` methods, since the returned type is `Box<dyn NetworkStream + Send>`. After this change, the modified impl will apply to `Box<dyn NetworkStream + Send>`, which was presumably always intended.
> Implement `AsTcpStream` for `Box<dyn AsTcpStream>`

- src/client/builder.rs
This PR changes `connect()` on `ClientBuilder` to also assume the `https` scheme is secure, instead of just `wss`.
This change is _required_ for an application I'm developing, in which a `https` URL is upgraded to a secure web socket (for Firefox Send v3 to be exact, using `https://host/api/upload` for web sockets).
It would be awesome if this change could be accepted and published to crates.io, as the crate I'm working on is dependent on this to work.
> Also assume websockets over HTTPS are secure

- Cargo.toml
- src/client/async.rs
- src/client/builder.rs
- src/codec/http.rs
- src/codec/ws.rs
- src/lib.rs
- src/server/async.rs
- src/server/sync.rs
- src/server/upgrade/async.rs
- src/stream.rs
- src/ws/util/mod.rs
Before:
* On `cargo build` there are 112 deps
* On `cargo test` there are 126 deps
After:
* On `cargo build` there are 95 deps
* On `cargo test` there are 122 deps
> Remove a lot of unnecessary tokio deps (udp, fs, uds and so on)

- src/server/mod.rs
Closes #153
This is how an error looks like:
```
Finished dev [unoptimized + debuginfo] target(s) in 2.33s
Running `target/debug/examples/async-server`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidConnection { stream: "...", parsed: "...", buffer: "...", error: Io(Custom { kind: ConnectionReset, error: StringError("Connection dropped before handshake could be read") }) }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Even if you don't map errors:
```
let f = server
.incoming()
.for_each(move |(upgrade, addr)| {
```
> Add a simple impl Debug for InvalidConnection

- src/server/async.rs
When you bind to a dynamically allocated port by specifying 0, it is necessary to query the socket after `bind()` to see which port was selected by the OS. A `local_addr()` wrapper is provided for sync. This change adds it for async.
> Provide an implementation of local_addr for Async servers

- src/client/builder.rs
This makes `ws://john:pswd@example.org/` to be correctly handled instead of being silently ignored.
Rationale: this project is supposedly implementing RFC6455 that states[1]:
URI scheme syntax
Using the ABNF [RFC5234] syntax and ABNF terminals from the URI
specification [RFC3986]:
"ws:" "//" authority path-abempty [ "?" query ]
And RFC3986 states[2] that 'authority' may include a username and password.
[1] https://tools.ietf.org/html/rfc6455#section-11.1.1
[2] https://tools.ietf.org/html/rfc3986#section-3.2.1
> Handle username/password from URL

- src/client/builder.rs
- src/result.rs
Fixes #233.
While this is theoretically a breaking change, I'm unsure if its that significant.
> Added StatusCodeError when receiving unexpected status code

- examples/async-client.rs
As mentioned in #244 , there is a not a ton of documentation regarding the design of the chat client in the async-client.rs example. I've added some documentation which I hope will clarify things a bit more for new users. If there are any fixes that need to be made before merging, please let me know and I will be happy to try and take care of them!
> Adding basic code comments to async-client example

- examples/async-client.rs
As far as i can tell, the server doesn't initiate the close handshake, so the client should just consider the handshake finished when it receives the acknowledgment and probably just wait for the server to close the underlying connection.
This stops if from trying to start a second close handshake.
It's not exactly clear to me how this avoids dropping the underlying connection before the server closes it now???
There is also a warning:
```
warning: unused `futures::stream::Select` in tuple element 0 that must be used
--> examples/async-client.rs:67:2
|
67 |     runtime.block_on(runner).unwrap();
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
= note: streams do nothing unless polled
```
Given how convoluted types get here, I haven't exactly …
> Async client example: Don't close twice

- src/result.rs
This PR provides a more informative error message when a `WebSocketOtherError` is displayed. The main driver of this change is vi/websocat#55, which would then indicate the concrete status code obtained from the server.
> Improve Display impl for WebSocketOtherError

- websocket-base/Cargo.toml
- websocket-base/src/header.rs
This other crate is being maintained, it offers better performances (when using the `asm` feature, especially [on AArch64](https://github.com/RustCrypto/hashes/pull/97)).  It also allows deduplicating SHA-1 crates in cargo-web.
> Replace sha1 crate with sha-1

- src/lib.rs
In order to use any of the connect functions I would be required to depend on native_tls directly. It would be easier if you exposed the version you depend on.
```
use native_tls::TlsConnector; //Errors out currently
use websocket::native_tls::{TlsConnector, Certificate}; //What I propose
let mut file = File::open("cert.pem")?;
let mut data:Vec<u8> = Vec::new();
file.read_to_end(&mut data);
let root_ca = Certificate::from_pem(&data)?;
let connector = TlsConnector::builder().add_root_certificate(root_ca).build()?;
let mut builder: ClientBuilder = ClientBuilder::from_url(&self.url);
let mut client = builder.connect(Some(connector))?;
```
> Expose native_tls as it's needed to use your API

- src/codec/http.rs
- src/lib.rs
- src/result.rs
- src/server/sync.rs
- src/server/upgrade/mod.rs
- websocket-base/src/result.rs
Remove deprecated usage of the `description` function and replace it with `to_string` function.
Remove deprecated usage of the `cause` function and replace it with `source` function.
> Remove deprecated usage of the "description" and "cause" functions

- src/result.rs
Without the gating `websocket` fails to compile if neither of the TLS features is enabled.
> Properly gate TLS error variants in Display impl
